### ISSUE TITLE
Creating SQL script to recreate database from github

### ISSUE THREAD

**Issue by smscoggi** [karanjadhav2508/kqsse17#22]
If we can't load/migrate Database into GitHub for others to download and use the data, we need to create it ourselves.

**Comment by alokozai** [comment]
I am creating database for my project and will be connected to my overall design structure. I will upload the whole file. For example if a user says "John" then it will be looked into database and compared, if the compare=true then marked present otherwise marked absent. Although I give other constraints of fraud or lets say if other students say the name. But I dont want to make it complicated. Is it related to this???

**Comment by karanjadhav2508** [comment]
So I'm using SQLite for Android which comes embedded.
Doesn't require an explicit running instance and uses local storage in the phone.
DB creation etc is handled on the fly. Doesn't need to be done manually as would be done by a traditional SQL admin

**Comment by smscoggi** [comment]
SQLite seems really convenient, unfortunately, I'm using MySQL at this time. 

Qaiss, yes that is helpful, though not related. I am asking how to create and use a SQL script to run automatically and create the database for whenever it's not already locally stored on the system the app is downloaded to.

**Comment by alokozai** [comment]
when is our demo due?

**Comment by karanjadhav2508** [comment]
Samantha, I have created a database and tables within it in the past in MS-SQL, though I don't remember the syntax. I think it's best you Google it for MySQL
If you stick to a relatively simple DB/table, then the creation isn't too difficult. Shouldn't take more than 1-2 hours I reckon.
Correct me if I'm wrong, but since you're building a web-app, how would it be downloaded to any system?

**Comment by smscoggi** [comment]
At this time haven't figured out how to turn it into a web app. Currently, it functions as a desktop app.

**Comment by smscoggi** [comment]
This functionality may be reopened. For now, it will be closed.
